site_name: 9 Line Defense Knowledgebase
site_url: https://aaron-knowledge.website-us-southeast-1.linodeobjects.com

repo_name: aaronfs07/9linedefense-knowledge
repo_url: https://github.com/aaronfs07/9linedefense-knowledge
edit_uri: edit/development/docs/

theme: 
  name: material
  palette:
    - scheme: default
      primary: red
      accent: blue grey
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
