jobs:
  mkdocs:
    name: Build and deploy mkdocs site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: jnanadarshan/mkdocs-build-action@v1

    - name: Configure AWS credentials
      uses: jakejarvis/s3-sync-action@master
      with:
        AWS_S3_ENDPOINT: us-southeast-1.linodeobjects.com
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-southeast-1

    - name: Sync output to S3
      run: |
        aws s3 sync ./site/ s3://my-s3-bucket --delete