name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  mkdocs:
    name: Build and deploy mkdocs site
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: jnanadarshan/mkdocs-build-action@v0.24

    - name: Configure AWS credentials
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete

      env:
        AWS_S3_ENDPOINT: https://us-southeast-1.linodeobjects.com
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-southeast-1
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_EC2_METADATA_DISABLED: true

    - name: Sync output to S3
      run: |
        aws s3 sync ./site/ s3://my-s3-bucket --delete